# Generated by Django 6.0.4 on 2026-04-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
