# Generated by Django 6.0.4 on 2026-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='reference',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
