# Generated by Django 6.0.4 on 2026-04-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('dci', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=50)),
                ('dosage', models.CharField(max_length=50)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.IntegerField()),
                ('stock_minimum', models.IntegerField()),
                ('date_expiration', models.DateField()),
                ('ordonnance_requise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='categories.category')),
            ],
        ),
    ]
